Feature/Provide clear error message when viewer fails to subscribe
millicast/vue-viewer-plugin pull request #83
Opened 2023-12-07 13:43 UTC by juanpiquerez

Added UX improvements at the moment the user fails to subscribe to the token. Whenever the following situations happen, we display an error message:
- Use case 1:  Viewer failed to view the stream due to Geo-blocking setting
- Use case 2: Viewer failed to view the stream due to missing subscribe token for the publishing token enable secure.

2023-12-11 13:53 UTC, NicolasInzua requested changes
I suggest a couple of changes to handle the error in a different way

2023-12-11 13:53 UTC, NicolasInzua commented on src/components/VideoPlayerContainer.vue
> +      message: (state) => state.message,
```suggestion
      error: (state) => state.error,
```

2023-12-11 13:53 UTC, NicolasInzua commented on src/components/VideoPlayerContainer.vue
> +        toast.error(this.message)
```suggestion
      if (newVal & this.error instanceof ConnectionError) {
        const { message } = this.error
        const toast = useToast()
        toast.error(message)
```

2023-12-11 13:53 UTC, NicolasInzua commented on src/store/modules/errors.js
> +}
It is necessary to create a subscribe error class, similar to the following (include it in another file):

```suggestion
}

class ConnectionError extends Error {
  constructor(message) {
    super(message);
    this.name = 'ConnectionError'
  }
}
```

2023-12-11 13:53 UTC, NicolasInzua commented on src/store/modules/errors.js
> +      state.message = message
```suggestion
    setError(state, error) {
      state.error= error
```

2023-12-11 13:53 UTC, NicolasInzua commented on src/store/modules/errors.js
> +  },
To simplify error handling and proper commit to the store

```suggestion
  },
  actions: {
    handleError({ commit }, { message }) {
      const error = new CustomError(message)
      commit('setError', error)
      commit('setShowError', true)
    },
}
```

2023-12-11 13:53 UTC, NicolasInzua commented on src/store/modules/errors.js
> +  message: '',
Identifying errors with strings is considered to be a form of a weak contract with the error, a class can be used to make it clearer what the error is.

```suggestion
  error: null,
```

2023-12-11 13:53 UTC, NicolasInzua commented on src/service/utils/viewConnection.js
> +      })
```suggestion
      ).catch((error) => {
        store.dispatch('Errors/handleError', { message: error.message })
      })
```

2023-12-13 16:46 UTC, tatiana-perera approved these changes

2023-12-13 16:46 UTC, merged