Feature/ Add toast visibility flag
millicast/vue-viewer-plugin pull request #93
Opened 2024-01-25 19:12 UTC by juanpiquerez

Viewer plugin should have a visibility toast option to be able to hide all toast notifications.

2024-01-26 15:20 UTC, R-Delfino95 requested changes

2024-01-26 15:20 UTC, R-Delfino95 commented on src/components/VideoPlayerSideVideoSources.vue
> +          this.toast.showToast('success', 'There was an error selecting the desired source, try again', { timeout: 5000 })
Should be error type, right?

2024-01-29 15:49 UTC, R-Delfino95 approved these changes

2024-01-30 15:41 UTC, tatiana-perera approved these changes

2024-01-30 15:50 UTC, tatiana-perera commented on README.md
> +| `hideToast`   | `String`          | Optional |  `null`              | Allows you to hide a specific type of toast, and you can hide more than one by separating them by ",". Possible values: 'succes
```suggestion
| `hideToast`   | `String`          | Optional |  `null`              | Allows to hide a specific type of toast, with the capability to hide multiple types simultaneously by `,`. Accepted values: 'success', 'error', 'warning', 'info'. |
```

2024-01-30 17:32 UTC, tatiana-perera commented on README.md
>  | `startingQuality` | `String` | Optional | Allows to start the stream at a specific resolution when available. Possible values: 'High', 'Medium', 'Low', <Number> specifying the desired frame height
```suggestion
| `startingQuality` | `String` | Optional | `null`| Allows to start the stream at a specific resolution when available. Possible values: 'High', 'Medium', 'Low', <Number> specifying the desired frame height (i.e. 360). |
```

2024-01-30 17:35 UTC, tatiana-perera commented on README.md
> +| `hideToast`   | `String`          | Optional |  `null`              | Allows to hide a specific type of toast, with the capability to hide multiple types simultaneously by `,`. Accepted values: 'su
```suggestion
| `hideToast`   | `String`          | Optional |  `null`              | Allows to hide a specific type of toast notification. To hide multiple toast types, separate them using `,`. Possible values: `success`, `error`, `warning`, `info`. |
```

2024-01-30 17:36 UTC, merged